Lab1: lab1.c
	gcc lab1.c -o Lab1

Lab2: lab2.c
	gcc lab2.c -o Lab2 -lm

Lab3: lab3.c
	gcc lab3.c -o Lab3

Lab4: lab4.c
	gcc lab4.c -o Lab4

Lab5: lab5.c
	gcc lab5.c -o Lab5

Lab6: lab6.c
	gcc lab6.c -o Lab6

Lab7: lab7.c
	gcc lab7.c -o Lab7	  

clean:
	rm Lab*
	
